[build]
  command = "npm run build"
  publish = "dist"
  base = "client"

[functions]
  directory = "functions"
  # Netlify will automatically detect and deploy Firebase Functions if linked correctly
  # Alternatively, configure deployment via GitHub Actions or Firebase CLI

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

